export const api = {
  main: "https://brixlogin.pkbit.co/",
  alarm: "https://brix.pkbit.co/alarm/",
  sensor: "https://brix.pkbit.co/sensor/",
  brixline: "https://brix.pkbit.co/brixline/",
  brixlinemin: "https://brix.pkbit.co/brixlinemin/",
  brixlinemax: "https://brix.pkbit.co/brixlinemax/",
  brixlinetarget: "https://brix.pkbit.co/brixlinetarget/",
  brix: "https://brix.pkbit.co/brix/",
  brixmin: "https://brix.pkbit.co/brixmin/",
  brixmax: "https://brix.pkbit.co/brixmax/",
  brixavg: "https://brix.pkbit.co/brixavg/",
  templine: "https://brix.pkbit.co/templine/",
  templinemin: "https://brix.pkbit.co/templinemin/",
  templinemax: "https://brix.pkbit.co/templinemax/",
  templinetarget: "https://brix.pkbit.co/templinetarget/",
  temp: "https://brix.pkbit.co/temp/",
  tempmin: "https://brix.pkbit.co/tempmin/",
  tempmax: "https://brix.pkbit.co/tempmax/",
  tempavg: "https://brix.pkbit.co/tempavg/",
};
